version: '3.8'

services:
  app:
    build: .
    restart: always
    container_name: java-backend
    ports:
      - "8080:8080"
    env_file:
      - .env.template
    environment:
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USER}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - GEMINI_KEY=${AI_GEMINI_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - PROJECT_ID=${PROJECT_ID}

    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: backend-db
    environment:
      POSTGRES_DB: ai_learning_tracker
      POSTGRES_USER: ${DATASOURCE_USER}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5455:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATASOURCE_USER} -d ai_learning_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    name: shared-network
    driver: bridge